Resources:
  ReportsStreamWatcherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      ManagedPolicyArns:
        -  arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
      Policies:
        - PolicyName: ResportsStreamWatcher
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - states:StartExecution
                Resource:
                  - '*'